### ISSUE TITLE
Earthgore - CD changes

### ISSUE THREAD

**Issue by Alphakilo** [inimicus/Cooldowns#15]
As of v6.0.5 (Update 26) Earthgores cooldown is down to 20 seconds

> Earthgore:
> 
>     This set now heals for 29700 health over 10 seconds, rather than 30000 over 6 seconds, to reduce the burst heal potential.
>     Reduced the cooldown to 20 seconds from 35 seconds.
- [Patchnotes](https://forums.elderscrollsonline.com/en/discussion/comment/6779134/#Comment_6779134)

**Comment by inimicus** [comment]
Resolved by #16.
